### ISSUE TITLE
Create style tiles for review

### ISSUE THREAD

**Issue by ohsk** [urbanlaunchpad/kotakita#2]

**Comment by ohsk** [comment]
![73223db2d1edee1ae9e92ec6e8ae3c47](https://cloud.githubusercontent.com/assets/1689222/4673726/acd11160-55a7-11e4-8dc8-c3c0d8fc93ee.jpg)

**Comment by buzoherbert** [comment]
Is that a colour palette?

**Comment by ohsk** [comment]
Ha not my proposed one for YKK, but an example of a "style tile", which is basically just a bunch of brand components to show the overall look and feel of an identity proposal.

**Comment by ohsk** [comment]
[Potential color palette](http://www.colourlovers.com/palette/540619/Funny_Like_the_Moon), drawing inspiration from Solo batik:
![image](https://cloud.githubusercontent.com/assets/1689222/4732716/dfb5adc2-59bf-11e4-8a7d-2f2cdc315ce1.png)

**Comment by ohsk** [comment]
Latest style tile, building off the feedback to use the full name KOTA KITA
![ykk_logo_concept_v2](https://cloud.githubusercontent.com/assets/1689222/4732928/64f95a22-59c2-11e4-8e42-0919e86355f8.png)

**Comment by ohsk** [comment]
Some slight variations on the logo type:

![ykk_logo_concept_v3-03](https://cloud.githubusercontent.com/assets/1689222/4746120/635540a0-5a44-11e4-8e9b-0fe8a909a5f7.png)
![ykk_logo_concept_v3-04](https://cloud.githubusercontent.com/assets/1689222/4746119/6353df08-5a44-11e4-9bcc-9208bdf2f00b.png)
![ykk_logo_concept_v3-05](https://cloud.githubusercontent.com/assets/1689222/4746121/635a9456-5a44-11e4-9376-a438b6140234.png)
